/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.mockito:mockito-core:5.8.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.8.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("com.github.ben-manes.caffeine:caffeine:3.2.3")
    implementation("org.rocksdb:rocksdbjni:8.11.3")
    implementation("com.esotericsoftware:kryo:5.5.0") // for serialization/deserialization

     // Add for benchmarking
    implementation("org.ehcache:ehcache:3.10.8")
    implementation("org.openjdk.jmh:jmh-core:1.37")
    annotationProcessor("org.openjdk.jmh:jmh-generator-annprocess:1.37")
    
    // Metrics
    implementation("io.dropwizard.metrics:metrics-core:4.2.19")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "tier_cache.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    // Set JVM arguments to help with RocksDB native library loading on ARM64
    jvmArgs(
        "-Djava.library.path=/opt/homebrew/lib:${System.getProperty("java.library.path")}",
        "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED"
    )
}

sourceSets {
    create("jmh") {
        java.srcDir("src/jmh/java")
        compileClasspath += sourceSets["main"].runtimeClasspath
        runtimeClasspath += sourceSets["main"].runtimeClasspath
    }
}

tasks.register<JavaExec>("runBenchmark") {
    group = "benchmark"
    classpath = sourceSets["jmh"].runtimeClasspath + sourceSets["main"].runtimeClasspath
    mainClass.set("tier_cache.benchmark.BenchmarkRunner")
    dependsOn("compileJmhJava")
}